# Use the official Python image as base image
FROM python:3.10

# Set the working directory in the container
WORKDIR /tg_app

# Copy the current directory contents into the container at /app
COPY . /tg_app

# Install any needed dependencies specified in requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Define environment variable
ENV NAME .env

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]