version: "3.9"
services:
  postgres:
    container_name: bd
    image: postgres:13.3
    environment:
      POSTGRES_DB: "quickapp"
      POSTGRES_USER: "darkfos"
      POSTGRES_PASSWORD: "7709"
    ports:
      - "5599:5598"
    restart: always
    networks:
      - my_network
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - my_network
  tg_bot:
    container_name: tg_bot
    build: 
      context: .
      dockerfile: Dockerfile.bot
    ports:
      - "8293:8349"
    restart: always
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - my_network

networks:
  my_network:
    driver: bridge