"""essage=Upgrade user table, add photo - nullable True

Revision ID: 2cac498731d5
Revises: f8841157d2eb
Create Date: 2024-04-29 20:29:22.889824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cac498731d5"
down_revision: Union[str, None] = "f8841157d2eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_table", sa.Column("photo", sa.LargeBinary(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_table", "photo")
    # ### end Alembic commands ###
