"""Add game_count

Revision ID: 42c678a6907b
Revises: 6adcac1aced7
Create Date: 2024-04-29 03:04:21.907959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42c678a6907b"
down_revision: Union[str, None] = "6adcac1aced7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_table", sa.Column("game_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_table", "game_count")
    # ### end Alembic commands ###
