"""Create tables

Revision ID: 5ab1bc6d9b8f
Revises: 9c3c1b9b8481
Create Date: 2024-04-27 01:01:54.018988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ab1bc6d9b8f"
down_revision: Union[str, None] = "9c3c1b9b8481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
