"""Update UserTable

Revision ID: 6adcac1aced7
Revises: fbb94a007aee
Create Date: 2024-04-29 01:14:43.067828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6adcac1aced7"
down_revision: Union[str, None] = "fbb94a007aee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_table", ["telegram_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_table", type_="unique")
    # ### end Alembic commands ###
