"""Init db

Revision ID: 7b1f2037650a
Revises: 258f3c79a9de
Create Date: 2024-04-26 02:59:29.960957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b1f2037650a"
down_revision: Union[str, None] = "258f3c79a9de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("history_table")
    op.drop_table("review_table")
    op.drop_table("user_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_table",
        sa.Column(
            "telegram_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "name_user",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "date_create",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_update",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('user_table_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="user_table_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "review_table",
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_table.id"], name="review_table_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="review_table_pkey"),
    )
    op.create_table(
        "history_table",
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "right_word", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "lose_word", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "procent_game",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_table.id"], name="history_table_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="history_table_pkey"),
    )
    # ### end Alembic commands ###
