"""Update user table

Revision ID: 88175f77f154
Revises: 2cac498731d5
Create Date: 2024-04-29 21:33:26.572503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88175f77f154"
down_revision: Union[str, None] = "2cac498731d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table",
        "photo",
        existing_type=postgresql.BYTEA(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_table",
        "photo",
        existing_type=sa.TEXT(),
        type_=postgresql.BYTEA(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
