"""tables db

Revision ID: b0e35e11db39
Revises: 04fe571888ff
Create Date: 2024-04-30 04:50:19.992137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0e35e11db39"
down_revision: Union[str, None] = "04fe571888ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_table",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("name_user", sa.String(length=500), nullable=False),
        sa.Column("photo", sa.TEXT(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("game_count", sa.Integer(), nullable=True),
        sa.Column("date_create", sa.Date(), nullable=False),
        sa.Column("date_update", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "history_table",
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("right_word", sa.Integer(), nullable=False),
        sa.Column("lose_word", sa.Integer(), nullable=False),
        sa.Column("procent_game", sa.Double(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review_table",
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_table.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_table")
    op.drop_table("history_table")
    op.drop_table("user_table")
    # ### end Alembic commands ###
