"""Update cascade tables

Revision ID: f8841157d2eb
Revises: bedac508119a
Create Date: 2024-04-29 16:27:35.668730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8841157d2eb"
down_revision: Union[str, None] = "bedac508119a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "history_table_user_id_fkey", "history_table", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "history_table",
        "user_table",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "review_table_user_id_fkey", "review_table", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "review_table",
        "user_table",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "review_table", type_="foreignkey")
    op.create_foreign_key(
        "review_table_user_id_fkey",
        "review_table",
        "user_table",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "history_table", type_="foreignkey")
    op.create_foreign_key(
        "history_table_user_id_fkey",
        "history_table",
        "user_table",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
